'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Plus, Trash2, Play, Copy, ChevronDown, ChevronRight, Zap } from 'lucide-react'
import { getAllAgents, AgentConfig } from '@/lib/agents'

interface Task {
  id: string
  description: string
  agentId: string
  expectedOutput: string
  tools: string[]
  async: boolean
}

interface Crew {
  name: string
  description: string
  process: 'sequential' | 'hierarchical'
  managerAgentId: string
  agents: string[]
  tasks: Task[]
  verbose: boolean
  memory: boolean
}

function newTask(): Task {
  return {
    id: Math.random().toString(36).slice(2),
    description: '',
    agentId: '',
    expectedOutput: '',
    tools: [],
    async: false,
  }
}

const TASK_TOOL_OPTIONS = ['web-search', 'code-execute', 'file-read', 'file-write', 'api-call', 'memory-recall', 'summarize', 'analyze']

function generatePython(crew: Crew, agents: AgentConfig[]): string {
  const agentMap = new Map(agents.map(a => [a.id, a]))
  const crewAgents = crew.agents.map(id => agentMap.get(id)).filter(Boolean) as AgentConfig[]

  const agentVars = crewAgents.map(a =>
    `${a.name.toLowerCase().replace(/\W+/g, '_')} = Agent(
    role="${a.name}",
    goal="${a.description || `Perform ${a.type} tasks efficiently`}",
    backstory="You are ${a.name}, an AI agent specializing in ${a.type.toLowerCase()} tasks.",
    tools=[${(a.tools ?? []).map(t => `${t.replace(/-/g, '_')}_tool`).join(', ')}],
    verbose=${crew.verbose ? 'True' : 'False'},
    allow_delegation=${crew.process === 'hierarchical' ? 'True' : 'False'},
)`).join('\n\n')

  const taskVars = crew.tasks.map((t, i) => {
    const agentVar = agentMap.get(t.agentId)?.name.toLowerCase().replace(/\W+/g, '_') || 'agent'
    return `task_${i + 1} = Task(
    description="${t.description || `Task ${i + 1}`}",
    expected_output="${t.expectedOutput || 'Completed task output'}",
    agent=${agentVar},
    tools=[${t.tools.map(tool => `${tool.replace(/-/g, '_')}_tool`).join(', ')}],
    async_execution=${t.async ? 'True' : 'False'},
)`}).join('\n\n')

  const managerLine = crew.process === 'hierarchical' && crew.managerAgentId
    ? `\n    manager_agent=${agentMap.get(crew.managerAgentId)?.name.toLowerCase().replace(/\W+/g, '_') || 'manager'},`
    : ''

  return `from crewai import Agent, Task, Crew, Process
from crewai_tools import *

# ============================================================
# ${crew.name}
# ${crew.description}
# Generated by Agent Ops
# ============================================================

# --- Agents ---
${agentVars}

# --- Tasks ---
${taskVars}

# --- Crew ---
crew = Crew(
    agents=[${crewAgents.map(a => a.name.toLowerCase().replace(/\W+/g, '_')).join(', ')}],
    tasks=[${crew.tasks.map((_, i) => `task_${i + 1}`).join(', ')}],
    process=Process.${ crew.process === 'hierarchical' ? 'hierarchical' : 'sequential'},${managerLine}
    verbose=${crew.verbose ? 'True' : 'False'},
    memory=${crew.memory ? 'True' : 'False'},
)

# --- Run ---
result = crew.kickoff()
print(result)
`
}

function generateYAML(crew: Crew, agents: AgentConfig[]): string {
  const agentMap = new Map(agents.map(a => [a.id, a]))
  const crewAgents = crew.agents.map(id => agentMap.get(id)).filter(Boolean) as AgentConfig[]

  const agentsYaml = crewAgents.map(a => `  ${a.name.toLowerCase().replace(/\W+/g, '_')}:
    role: "${a.name}"
    goal: "${a.description || `Perform ${a.type} tasks`}"
    backstory: "AI agent specializing in ${a.type.toLowerCase()}"
    tools: [${(a.tools ?? []).join(', ')}]`).join('\n')

  const tasksYaml = crew.tasks.map((t, i) => `  task_${i + 1}:
    description: "${t.description}"
    expected_output: "${t.expectedOutput}"
    agent: ${agentMap.get(t.agentId)?.name.toLowerCase().replace(/\W+/g, '_') || 'agent'}
    async: ${t.async}`).join('\n')

  return `# ${crew.name}
# Generated by Agent Ops

crew:
  name: "${crew.name}"
  description: "${crew.description}"
  process: ${crew.process}
  verbose: ${crew.verbose}
  memory: ${crew.memory}

agents:
${agentsYaml}

tasks:
${tasksYaml}
`
}

export default function CrewBuilder() {
  const allAgents = getAllAgents()
  const [crew, setCrew] = useState<Crew>({
    name: 'My Crew',
    description: '',
    process: 'sequential',
    managerAgentId: '',
    agents: [],
    tasks: [newTask()],
    verbose: true,
    memory: false,
  })
  const [outputFormat, setOutputFormat] = useState<'python' | 'yaml'>('python')
  const [showOutput, setShowOutput] = useState(false)
  const [copied, setCopied] = useState(false)
  const [expandedTask, setExpandedTask] = useState<string | null>(crew.tasks[0].id)

  const set = (key: keyof Crew, val: unknown) => setCrew(c => ({ ...c, [key]: val }))

  const toggleAgent = (id: string) => {
    const agents = crew.agents.includes(id)
      ? crew.agents.filter(a => a !== id)
      : [...crew.agents, id]
    setCrew(c => ({ ...c, agents }))
  }

  const addTask = () => {
    const t = newTask()
    setCrew(c => ({ ...c, tasks: [...c.tasks, t] }))
    setExpandedTask(t.id)
  }

  const updateTask = (id: string, key: keyof Task, val: unknown) => {
    setCrew(c => ({ ...c, tasks: c.tasks.map(t => t.id === id ? { ...t, [key]: val } : t) }))
  }

  const deleteTask = (id: string) => {
    setCrew(c => ({ ...c, tasks: c.tasks.filter(t => t.id !== id) }))
  }

  const toggleTaskTool = (taskId: string, tool: string) => {
    setCrew(c => ({
      ...c,
      tasks: c.tasks.map(t => {
        if (t.id !== taskId) return t
        return { ...t, tools: t.tools.includes(tool) ? t.tools.filter(x => x !== tool) : [...t.tools, tool] }
      })
    }))
  }

  const code = outputFormat === 'python'
    ? generatePython(crew, allAgents)
    : generateYAML(crew, allAgents)

  const handleCopy = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="flex h-full min-h-0">
      {/* Left: Config */}
      <div className="w-[460px] flex-shrink-0 flex flex-col border-r border-white/5 overflow-y-auto">
        <div className="px-6 py-5 border-b border-white/5">
          <h2 className="text-white font-bold text-sm tracking-wide flex items-center gap-2">
            <Zap className="w-4 h-4 text-violet-400" />
            CrewAI Builder
          </h2>
          <p className="text-slate-500 text-xs mt-1">Design multi-agent crews and export ready-to-run code</p>
        </div>

        <div className="flex-1 px-6 py-5 space-y-6">
          {/* Crew identity */}
          <div className="space-y-3">
            <input
              value={crew.name}
              onChange={e => set('name', e.target.value)}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white font-semibold placeholder-slate-600 focus:outline-none focus:border-violet-500/50"
              placeholder="Crew name"
            />
            <textarea
              value={crew.description}
              onChange={e => set('description', e.target.value)}
              rows={2}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-slate-300 placeholder-slate-600 focus:outline-none focus:border-violet-500/50 resize-none"
              placeholder="What does this crew accomplish?"
            />
          </div>

          {/* Process */}
          <div>
            <label className="text-xs text-slate-500 uppercase tracking-widest block mb-2">Process</label>
            <div className="grid grid-cols-2 gap-2">
              {(['sequential', 'hierarchical'] as const).map(p => (
                <button
                  key={p}
                  onClick={() => set('process', p)}
                  className="py-3 rounded-xl text-xs font-semibold border transition-all capitalize"
                  style={{
                    background: crew.process === p ? 'rgba(168,85,247,0.2)' : 'rgba(255,255,255,0.04)',
                    borderColor: crew.process === p ? 'rgba(168,85,247,0.5)' : 'rgba(255,255,255,0.08)',
                    color: crew.process === p ? '#a855f7' : '#64748b',
                  }}
                >
                  {p}
                </button>
              ))}
            </div>
          </div>

          {/* Manager (hierarchical only) */}
          <AnimatePresence>
            {crew.process === 'hierarchical' && (
              <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }}>
                <label className="text-xs text-slate-500 uppercase tracking-widest block mb-2">Manager Agent</label>
                <select
                  value={crew.managerAgentId}
                  onChange={e => set('managerAgentId', e.target.value)}
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-violet-500/50"
                  style={{ background: 'rgba(255,255,255,0.05)' }}
                >
                  <option value="">Select manager...</option>
                  {allAgents.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                </select>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Options */}
          <div className="flex gap-4">
            {([['verbose', 'Verbose'], ['memory', 'Memory']] as const).map(([key, label]) => (
              <button
                key={key}
                onClick={() => set(key, !crew[key])}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold border transition-all flex-1 justify-center"
                style={{
                  background: crew[key] ? 'rgba(16,185,129,0.15)' : 'rgba(255,255,255,0.04)',
                  borderColor: crew[key] ? 'rgba(16,185,129,0.4)' : 'rgba(255,255,255,0.08)',
                  color: crew[key] ? '#10b981' : '#64748b',
                }}
              >
                <span className={`w-2 h-2 rounded-full ${crew[key] ? 'bg-emerald-400' : 'bg-slate-600'}`} />
                {label}
              </button>
            ))}
          </div>

          {/* Agent picker */}
          <div>
            <label className="text-xs text-slate-500 uppercase tracking-widest block mb-3">
              Crew Members <span className="text-slate-600">({crew.agents.length} selected)</span>
            </label>
            <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
              {allAgents.map(a => {
                const selected = crew.agents.includes(a.id)
                return (
                  <button
                    key={a.id}
                    onClick={() => toggleAgent(a.id)}
                    className="w-full flex items-center gap-3 px-3 py-2.5 rounded-xl border transition-all"
                    style={{
                      background: selected ? `${a.accent}12` : 'rgba(255,255,255,0.03)',
                      borderColor: selected ? `${a.accent}40` : 'rgba(255,255,255,0.06)',
                    }}
                  >
                    <span className="text-base w-6 text-center" style={{ color: a.accent }}>{a.avatar}</span>
                    <div className="flex-1 text-left">
                      <div className="text-xs font-semibold text-white">{a.name}</div>
                      <div className="text-[10px] text-slate-600">{a.type}</div>
                    </div>
                    <div
                      className="w-4 h-4 rounded border flex items-center justify-center transition-all"
                      style={{
                        borderColor: selected ? a.accent : 'rgba(255,255,255,0.15)',
                        background: selected ? a.accent : 'transparent',
                      }}
                    >
                      {selected && <span className="text-white text-[10px]">✓</span>}
                    </div>
                  </button>
                )
              })}
            </div>
          </div>

          {/* Tasks */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <label className="text-xs text-slate-500 uppercase tracking-widest">
                Tasks <span className="text-slate-600">({crew.tasks.length})</span>
              </label>
              <button
                onClick={addTask}
                className="flex items-center gap-1 text-xs text-violet-400 hover:text-violet-300 transition-colors"
              >
                <Plus className="w-3 h-3" /> Add Task
              </button>
            </div>
            <div className="space-y-2">
              {crew.tasks.map((task, idx) => {
                const assignedAgent = allAgents.find(a => a.id === task.agentId)
                const expanded = expandedTask === task.id
                return (
                  <div key={task.id} className="rounded-xl border border-white/8 overflow-hidden">
                    <button
                      onClick={() => setExpandedTask(expanded ? null : task.id)}
                      className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-white/3 transition-colors"
                    >
                      <span className="text-xs font-mono text-slate-600 w-4">#{idx + 1}</span>
                      <span className="flex-1 text-xs text-slate-300 truncate">
                        {task.description || `Task ${idx + 1}`}
                      </span>
                      {assignedAgent && (
                        <span className="text-xs" style={{ color: assignedAgent.accent }}>{assignedAgent.avatar}</span>
                      )}
                      {expanded ? <ChevronDown className="w-3 h-3 text-slate-600" /> : <ChevronRight className="w-3 h-3 text-slate-600" />}
                    </button>
                    <AnimatePresence>
                      {expanded && (
                        <motion.div
                          initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }}
                          className="overflow-hidden border-t border-white/5"
                        >
                          <div className="px-4 py-3 space-y-3">
                            <textarea
                              value={task.description}
                              onChange={e => updateTask(task.id, 'description', e.target.value)}
                              rows={2}
                              className="w-full bg-white/5 border border-white/8 rounded-lg px-3 py-2 text-xs text-slate-300 placeholder-slate-600 focus:outline-none focus:border-violet-500/40 resize-none"
                              placeholder="Task description..."
                            />
                            <input
                              value={task.expectedOutput}
                              onChange={e => updateTask(task.id, 'expectedOutput', e.target.value)}
                              className="w-full bg-white/5 border border-white/8 rounded-lg px-3 py-2 text-xs text-slate-300 placeholder-slate-600 focus:outline-none focus:border-violet-500/40"
                              placeholder="Expected output..."
                            />
                            <select
                              value={task.agentId}
                              onChange={e => updateTask(task.id, 'agentId', e.target.value)}
                              className="w-full bg-white/5 border border-white/8 rounded-lg px-3 py-2 text-xs text-white focus:outline-none focus:border-violet-500/40"
                              style={{ background: 'rgba(255,255,255,0.05)' }}
                            >
                              <option value="">Assign to agent...</option>
                              {crew.agents.map(id => {
                                const a = allAgents.find(ag => ag.id === id)
                                return a ? <option key={id} value={id}>{a.avatar} {a.name}</option> : null
                              })}
                            </select>
                            <div className="flex flex-wrap gap-1">
                              {TASK_TOOL_OPTIONS.map(t => (
                                <button
                                  key={t}
                                  onClick={() => toggleTaskTool(task.id, t)}
                                  className="px-2 py-0.5 rounded text-[10px] border transition-all"
                                  style={{
                                    background: task.tools.includes(t) ? 'rgba(168,85,247,0.2)' : 'rgba(255,255,255,0.04)',
                                    borderColor: task.tools.includes(t) ? 'rgba(168,85,247,0.5)' : 'rgba(255,255,255,0.08)',
                                    color: task.tools.includes(t) ? '#a855f7' : '#64748b',
                                  }}
                                >
                                  {t}
                                </button>
                              ))}
                            </div>
                            <div className="flex items-center justify-between">
                              <button
                                onClick={() => updateTask(task.id, 'async', !task.async)}
                                className="flex items-center gap-2 text-xs"
                                style={{ color: task.async ? '#10b981' : '#64748b' }}
                              >
                                <span className={`w-2 h-2 rounded-full ${task.async ? 'bg-emerald-400' : 'bg-slate-600'}`} />
                                Async
                              </button>
                              {crew.tasks.length > 1 && (
                                <button onClick={() => deleteTask(task.id)} className="text-slate-600 hover:text-red-400 transition-colors">
                                  <Trash2 className="w-3.5 h-3.5" />
                                </button>
                              )}
                            </div>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Generate button */}
          <motion.button
            onClick={() => setShowOutput(true)}
            whileHover={{ scale: 1.01 }}
            whileTap={{ scale: 0.98 }}
            className="w-full py-3.5 rounded-xl font-semibold text-sm flex items-center justify-center gap-2 text-white"
            style={{ background: 'linear-gradient(135deg, #7c3aed, #a855f7)', boxShadow: '0 0 20px #a855f740' }}
          >
            <Play className="w-4 h-4" />
            Generate Code
          </motion.button>
        </div>
      </div>

      {/* Right: Output */}
      <div className="flex-1 flex flex-col min-w-0">
        <div className="flex items-center gap-3 px-6 py-4 border-b border-white/5 flex-shrink-0">
          <div className="flex gap-1 rounded-lg p-1" style={{ background: 'rgba(255,255,255,0.05)' }}>
            {(['python', 'yaml'] as const).map(f => (
              <button
                key={f}
                onClick={() => setOutputFormat(f)}
                className="px-4 py-1.5 rounded-md text-xs font-semibold transition-all uppercase tracking-wide"
                style={{
                  background: outputFormat === f ? 'rgba(168,85,247,0.3)' : 'transparent',
                  color: outputFormat === f ? '#c084fc' : '#64748b',
                }}
              >
                {f}
              </button>
            ))}
          </div>
          <button
            onClick={handleCopy}
            className="ml-auto flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold border transition-all"
            style={{
              background: copied ? 'rgba(16,185,129,0.15)' : 'rgba(255,255,255,0.05)',
              borderColor: copied ? 'rgba(16,185,129,0.4)' : 'rgba(255,255,255,0.1)',
              color: copied ? '#10b981' : '#94a3b8',
            }}
          >
            <Copy className="w-3.5 h-3.5" />
            {copied ? 'Copied!' : 'Copy'}
          </button>
        </div>

        <div className="flex-1 overflow-auto p-6">
          <pre className="text-xs font-mono text-slate-300 leading-relaxed whitespace-pre-wrap" style={{ tabSize: 4 }}>
            <code>{showOutput ? code : '# Click "Generate Code" to see your crew configuration here.\n# Configure agents and tasks on the left, then generate.'}</code>
          </pre>
        </div>
      </div>
    </div>
  )
}
